<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions targetNamespace="http://www.hello.org/HelloNs"  
	xmlns:tns="http://www.hello.org/HelloNs"
	xmlns:ns0="http://www.hello.org/HelloNs"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
	xmlns:wsp="http://www.w3.org/ns/ws-policy"
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:wsoma="http://schemas.xmlsoap.org/ws/2004/09/policy/optimizedmimeserialization"
	xmlns:wsa="http://www.w3.org/2005/08/addressing" 
	xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
	xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
	xmlns:wsrmp="http://docs.oasis-open.org/ws-rx/wsrmp/200702"
	xmlns:wsat="http://schemas.xmlsoap.org/ws/2004/10/wsat"
	xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"
	xmlns:wst="http://docs.oasis-open.org/ws-sx/ws-trust/200512"
	xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex"	
>
	<wsdl:types>
		<xs:schema>
			<xs:import schemaLocation="HelloNs.xsd" namespace="http://www.hello.org/HelloNs"/>
		</xs:schema>
	</wsdl:types>

		<wsdl:message name="IHello_SayHello_InputMessage">
			<wsdl:part name="parameters" element="ns0:SayHello"/>
		</wsdl:message>

		<wsdl:message name="IHello_SayHello_OutputMessage">
			<wsdl:part name="parameters" element="ns0:SayHelloResponse"/>
		</wsdl:message>

		<wsdl:portType name="IHello">
			<wsdl:operation name="SayHello">
				<wsdl:input wsaw:action="http://www.hello.org/HelloNs/IHello/SayHello" message="ns0:IHello_SayHello_InputMessage"/>
				<wsdl:output wsaw:action="http://www.hello.org/HelloNs/IHello/SayHelloResponse" message="ns0:IHello_SayHello_OutputMessage"/>
			</wsdl:operation>
		</wsdl:portType>

	<wsdl:binding name="IHello_HttpSoap11_Binding" type="ns0:IHello">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="SayHello">
			<soap:operation style="document" soapAction="http://www.hello.org/HelloNs/IHello/SayHello"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="HelloService">
		<wsdl:port name="IHello_HttpSoap11_Port" binding="ns0:IHello_HttpSoap11_Binding">
			<soap:address location="http://www.tempuri.org"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
